# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_hrvhra_wrappers", use_symbols = TRUE, package_name = "hrvhra")

#' @usage NULL
#' @useDynLib hrvhra, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Create a new RRRuns object and return the runs analysis
#' @param rr Vector of RR intervals
#' @param annotations Vector of annotations (0 for normal beats, non-zero for abnormal)
#' @param write_last_run Whether to include the last run in the analysis
#' @return A list containing the runs analysis
#' @export
analyze_rr_runs <- function(rr, annotations, write_last_run) .Call(wrap__analyze_rr_runs, rr, annotations, write_last_run)

#' Get a summary of runs analysis
#' @param rr Vector of RR intervals
#' @param annotations Vector of annotations (0 for normal beats, non-zero for abnormal)
#' @param write_last_run Whether to include the last run in the analysis
#' @return A vector of data with rows and columns as attributes
#' @export
get_runs_summary <- function(rr, annotations, write_last_run) .Call(wrap__get_runs_summary, rr, annotations, write_last_run)


# nolint end
