# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_hrvhra_wrappers", use_symbols = TRUE, package_name = "hrvhra")

#' @usage NULL
#' @useDynLib hrvhra, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Create a new RRRuns object and return the runs analysis
#' @param rr Vector of RR intervals
#' @param annotations Vector of annotations (0 for normal beats, non-zero for abnormal)
#' @param write_last_run Whether to include the last run in the analysis
#' @return A list containing the runs analysis
#' @export
analyze_rr_runs <- function(rr, annotations, write_last_run) .Call(wrap__analyze_rr_runs, rr, annotations, write_last_run)

#' Get a summary of runs analysis
#' @param rr Vector of RR intervals
#' @param annotations Vector of annotations (0 for normal beats, non-zero for abnormal)
#' @param write_last_run Whether to include the last run in the analysis
#' @return A vector of data with rows and columns as attributes
#' @export
get_runs_summary <- function(rr, annotations, write_last_run) .Call(wrap__get_runs_summary, rr, annotations, write_last_run)

#' Function to trim trailing zeros
#' @param v Numeric vector
#' @return A vector with trimmed trailing zeros
trim_trailing_zeros <- function(v) {
  if (all(v == 0)) return(integer(0))  # Return empty vector if all elements are zero
  v[1:(length(v) - which.max(rev(v) != 0) + 1)]
}

#' Function giving names to vector elements
#' @param v numeric vector
#' @param stem stem of the name for vector elements
#' @param return numeric vector with named elements
name_elements <- function(v, stem) {
  if (length(v) == 0) return(NULL)
  names <- paste0(rep(stem, length(v)), as.character(1:length(v)))
  names(v) <- names
  return(v)
}

#' Get a summary of runs analysis using rust code
#' @param rr Vector of RR intervals
#' @param annotations Vector of annotations (0 for normal beats, non-zero for abnormal)
#' @return a list with results for runs counts and results for runs variances
#' @export
getruns_rust <- function(rr, annotations) {
  result <- get_runs_summary(rr, annotations, TRUE)
  counts_results_matrix <- do.call(cbind, result$runs_counts)
  vars_results_matrix <- do.call(cbind, result$runs_vars)
  counts_result <- list(
    decelerations = trim_trailing_zeros(counts_results_matrix[2, ]) %>% name_elements(., "DR"),
    accelerations = trim_trailing_zeros(counts_results_matrix[1, ]) %>% name_elements(., "AR"),
    neutral = trim_trailing_zeros(counts_results_matrix[3, ]) %>% name_elements(., "NR")
  )
  vars_result_Var1 <- list(
    decelerations = trim_trailing_zeros(vars_results_matrix[2, ]) %>% name_elements(., "SD1_DR"),
    accelerations = trim_trailing_zeros(vars_results_matrix[1, ]) %>% name_elements(., "SD1_AR"),
    neutral = trim_trailing_zeros(vars_results_matrix[3, ]) %>% name_elements(., "SD1_NR")
  )
  vars_result_Var2 <- list(
    decelerations = trim_trailing_zeros(vars_results_matrix[5, ]) %>% name_elements(., "DR"),
    accelerations = trim_trailing_zeros(vars_results_matrix[4, ]) %>% name_elements(., "AR"),
    neutral = trim_trailing_zeros(vars_results_matrix[6, ]) %>% name_elements(., "NR")
  )
  result = list(runs_counts = counts_result, runs_vars = list(var1 = vars_result_Var1, var2 = vars_result_Var2))

  result
}

#' Get the sample entropy for a signal
#' @param signal signal for which the sample entropy will be calculated
#' @param m embedding dimension - int
#' @param r comparison radius - float
#' @return a float
#' @export
samp_en <- function(signal, m, r) .Call(wrap__samp_en, signal, m, r)


# nolint end
